### ISSUE TITLE
RTTI dump on an x64 app trimming first 2 letters

### ISSUE THREAD

**Issue by BanjosDen** [colinsenner/rtti-plugin-x64dbg#1]
![image](https://github.com/colinsenner/rtti-plugin-x64dbg/assets/29569985/f90d603d-b02d-4541-b19e-c980266dc4b5)

Looking here you can see the decorated name suggests "widgetuigame" as the class name, but in the RTTI output it is just "dgetuigame". 

BTW so glad you've made this, I've been wanting RTTI inspection inside x64dbg for ages!

**Comment by colinsenner** [comment]
@BanjosDen , thanks a ton for the bug report. I'll take a look, I might be truncating the length of the string? I'll take a look and mock up this example. I can't live without knowing the class name easily either ;).

**Comment by Doliman100** [comment]
This issue happens due to lack of UNDNAME_TYPE_ONLY flag. It tries to parse a function declaration. This flag marks that it should parse only a type.
Description from `undname.hxx`:
```
#define UNDNAME_TYPE_ONLY               (0x2000)    // Input is just a type encoding; compose an abstract declarator
```
The definition of the `__UNDNAME_NAME_EX/__unDNameEx()` function, which is almost the same as the `UnDecorateSymbolName()` function, can be found in MSVC build tools location:
`C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\crt\src\vcruntime\undname.cxx`
Also take a look at the `UnDecorator` class.
Fork with fix and binaries: https://github.com/Doliman100/rtti-plugin-x64dbg/releases

**Comment by colinsenner** [comment]
Closed, merged @Doliman100 's fix into `main`.
